import { getServerSession } from 'next-auth'
import SessionProvider from '../components/SessionProvider'
import SideBar from '../components/SideBar'
import '../styles/globals.css'
import { authOptions } from '../pages/api/auth/[...nextauth]'
import Login from '../components/Login'

export const metadata = {
  description: 'Generated by Next.js',
}

type Props = {
  children: React.ReactNode
}

export default async function RootLayout({ children }: Props) {

  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
            {!session ? LOG_IN() : APP({children})}
        </SessionProvider>
      </body>
    </html>
  )
}

const APP = ({children}: Props) => {
  return (
  <div className="flex">
    <SideBar />
              
    {/* Provider for notifications */}

    {/* Main app */}
    <div className="bg-slate-700 flex-1">{children}</div>
  </div>)
}

const LOG_IN = () => {
  return (<>
    <Login />
  </>)
}